apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: redis-deployment
  name: redis-deployment
  namespace: mynamespace
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-deployment
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdates
    template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
      - image: redis
        imagePullPolicy: never
        name: redisdgess
        ports:
        - containerPort: 7000
          protocol: TCP
