apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: coustomimage-controller
  labels:
    app: coustomworld
spec:
  replicas: 4
  selector:
    matchLabels:
      app: coustomworld
  template:
    metadata:
      labels:
        app: coustomworld
    spec:
      containers:
      - name: k8s-demo
        image: lakshman345/puthontest
        ports:
        - name: nodejs-port
          containerPort: 3002
