apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld-controller
  labels:
    app: helloworld
spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        spec:
      containers:
      - name: rkundanala
      image: rkundanala/dockerimage-new
        imagePullPolicy: Always
      command: [ "echo", "SUCCESS" ]
EOF
      
