apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: python-controller
  labels:
    app: pythonhelloworld
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pythonhelloworld
  template:
    metadata:
      labels:
        app: pythonhelloworld
        spec:
      containers:
      - name: rkundanala
      image: rkundanala/dockerimage-new
       ports:
        - name: python:2.7
          containerPort: 8080
      
