apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: rkundanala/redis-image
        ports:
          containerPort: 80
        livenessProbe:
            tcpSocket:
             port: 80
          httpGet:
            path: /
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
            tcpSocket:
             port: 80
          httpGet:
            path: /
          initialDelaySeconds: 15
          timeoutSeconds: 30
