apiVersion: v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: k8s-demo
        image: rkundanala/redis-image
        ports:
        - name: redis-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: redis-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: redis-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
